Hardware adc spi
SSL-Roots/FrootsPi pull request #19
Opened 2021-10-24 04:30 UTC by Horie-Yuya

メインバッテリ（LiPo）とサブバッテリ（９V電池）の電圧と状態を取得できるようにしたので確認お願いします。
ros2 topic echo /battery_voltage 
ros2 topic echo /ups_voltage 

statusの中身は、
# バッテリー電圧状態の定義
uint8 BATTERY_VOLTAGE_STATUS_UNKNOWN = 0
uint8 BATTERY_VOLTAGE_STATUS_TOO_LOW = 1
uint8 BATTERY_VOLTAGE_STATUS_NEED_CHARGING  = 2
uint8 BATTERY_VOLTAGE_STATUS_OK  = 3
uint8 BATTERY_VOLTAGE_STATUS_FULL = 4

各閾値は、一旦暫定で以下閾値で判別
メインバッテリ閾値：12.8, 14.8, 15.5, 16.8　単位：V
サブバッテリ閾値　：6.5, 　6.8,　  8,      9　単位：V

2021-11-08 02:20 UTC, tilt-silvie requested changes
レビューしました！　少し直してほしいところがあるのでコメントしました

2021-11-08 02:20 UTC, tilt-silvie commented on frootspi_hardware/src/battery_monitor.cpp
> +    } else {
ここはelseから出したほうが見通し良さそうです

2021-11-08 02:20 UTC, tilt-silvie commented on frootspi_hardware/src/battery_monitor.cpp
> +  // Reference: http://ww1.microchip.com/downloads/jp/DeviceDoc/21034A_JP.pdf
リファレンスが書いてあるのいいですね　👍

2021-11-08 02:20 UTC, tilt-silvie commented on frootspi_hardware/src/battery_monitor.cpp
> +bool BatteryMonitor::control_register(const char channel, float * read_data)
関数名は`control_register`より`read_adc`が適していると思います

2021-11-13 02:33 UTC, Horie-Yuya commented on frootspi_hardware/src/battery_monitor.cpp
> +bool BatteryMonitor::control_register(const char channel, float * read_data)
たしかにそうですね、修正しました

2021-11-13 02:59 UTC, Horie-Yuya commented on frootspi_hardware/src/battery_monitor.cpp
> +    } else {
elseから出しました！
elseの処理がなくなったので、構文自体削除しました。

2021-11-13 03:16 UTC, Horie-Yuya commented
レビュー箇所修正完了しました！

2021-11-14 07:07 UTC, ShotaAk approved these changes
LGTM

2021-11-14 07:07 UTC, merged