Hardware adc i2c
SSL-Roots/FrootsPi pull request #21
Opened 2021-11-07 07:05 UTC by Horie-Yuya

キャパシタ電圧をモニタリングする機能を追加
ros2 topic echo /kicker_voltage  で電圧を監視した状態で、
ros2 service call /set_kicker_charging frootspi_msgs/srv/SetKickerCharging "{start_charging: true}"　で充電開始指示
電圧が上がっていることを確認お願いします。
ros2 service call /set_kicker_charging frootspi_msgs/srv/SetKickerCharging "{start_charging: false}"　で充電終了
ros2 service call /kick frootspi_msgs/srv/Kick "{kick_type: 3, kick_power: 0.0}"　で放電処理を実施して、確認終了

2021-11-08 02:30 UTC, tilt-silvie requested changes
こっちも軽くレビューしましたー
まだ動作確認はできてないです

2021-11-08 02:30 UTC, tilt-silvie commented on frootspi_hardware/src/capacitor_monitor.cpp
> +bool CapacitorMonitor::control_register(float * read_data)
関数名は　read_adc のほうが適切そうです

2021-11-13 03:36 UTC, Horie-Yuya commented on frootspi_hardware/src/capacitor_monitor.cpp
> +bool CapacitorMonitor::control_register(float * read_data)
修正完了しました

2021-11-13 03:44 UTC, Horie-Yuya commented
レビュー箇所修正完了しました。　adc_spiで指摘いただいていた部分も追加で修正しました。

2021-11-14 07:08 UTC, ShotaAk approved these changes
LGTM

2021-11-14 07:12 UTC, merged